spring:
  datasource:
    url: jdbc:postgresql://dpg-ckgvjsi12bvs73a0l29g-a:5432/league1
    username: diogo
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true